src/objects/Batch_Template__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Batch Template</label>
    <nameField>
        <label>BGE Batch Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Batch_Template_Field__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Template__c</fullName>
        <label>Batch Template</label>
        <referenceTo>Batch_Template__c</referenceTo>
        <relationshipLabel>Batch Template Fields</relationshipLabel>
        <relationshipName>Batch_Template_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>Integer value to specify the order of items in the grid.</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If set to true the value will be required in order to save the record.</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sticky_Field_Value__c</fullName>
        <description>This field stores the default value to be used if &quot;Sticky Field&quot; is true.</description>
        <inlineHelpText>This field stores the default value to be used if &quot;Sticky Field&quot; is true.</inlineHelpText>
        <label>Sticky Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sticky_Field_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked all Data Import records will have the specified field filled with the specified value, but it will not be shown in the grid. This is usefull in case that we have a constant value that we want to keep in the object but not show at the grid.</description>
        <inlineHelpText>If checked all Data Import records will have the specified field filled with the specified value, but it will not be shown in the grid. This is usefull in case that we have a constant value that we want to keep in the object but not show at the grid.</inlineHelpText>
        <label>Sticky Field Visibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sticky_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the field will be filled in with a default value.</description>
        <inlineHelpText>Indicates if the field will be filled in with a default value.</inlineHelpText>
        <label>Sticky Field</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Template Field</label>
    <nameField>
        <label>Batch Template Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Template Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DataImportBatch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Batch Template</label>
        <referenceTo>Batch_Template__c</referenceTo>
        <relationshipLabel>NPSP Data Import Batches</relationshipLabel>
        <relationshipName>NPSP_Data_Import_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NPSP Data Import Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPSP Data Import Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BGE_TemplateController.cls
public with sharing class BGE_TemplateController {

    public static Batch_Template__c templateRecord = new Batch_Template__c();
    public static DataImportBatch__c batchRecord = new DataImportBatch__c();
    public static Id templateId;
    public static String[] templateFieldNames = new String[]{};
    public static Batch_Template_Field__c[] templateFields;
    public static Batch_Template_Field__c[] templateFieldsToDelete;

    public BGE_TemplateController() {

    }

	//@AuraEnabled
    public static Id saveBatch (DataImportBatch__c batch, Id templateId) {

        Id batchId = null;
        batchRecord = batch;
        batchRecord.Batch_Template__c = templateId;

        // Insert batch
        if (batchRecord != null) {

           insert batchRecord;
           batchId = batchRecord.Id;
           System.debug('Batch data ' + batchRecord);
        }
        return batchId;
    }

    public static Id updateBatch (DataImportBatch__c batch, Id templateId) {

        Id batchId = null;
        batchRecord = batch;
        batchRecord.Batch_Template__c = templateId;

        // Insert batch
        if (batchRecord != null) {

           update batchRecord;
           batchId = batchRecord.Id;
        }
        return batchId;
    }

    //@AuraEnabled
    public static Boolean saveTemplate (Batch_Template__c newTemplate, Batch_Template_Field__c[] batchTemplateFields) {

        Boolean isSaved;
        templateRecord = newTemplate;
        templateFields = batchTemplateFields;
        // Insert template
        if (templateRecord != null) {

            try {
                insert templateRecord;
                saveTemplateFields(templateFields, templateRecord.Id);
                isSaved = true;
            }
            catch (Exception ex) {
                isSaved = false;
            }
        }
        return isSaved;
    }

    public static Boolean deleteTemplate (Id templateIdToDelete) {

        Boolean result;
        Batch_Template__c templateToDelete;
        Batch_Template__c[] templates = [SELECT Id FROM Batch_Template__c WHERE Id = :templateIdToDelete LIMIT 1];
        DataImportBatch__c[] batches = [SELECT Id, Batch_Template__c FROM DataImportBatch__c WHERE Batch_Template__c = :templateIdToDelete LIMIT 10000];

        if (!templates.isEmpty() && batches.isEmpty()) {

            templateToDelete = templates[0];

            try {
                delete templateToDelete;
                result = true;
            }
            catch(Exception ex) {
                result = false;
            }
        }
        else {
            result = false;
        }
        return result;
    }

    public static Boolean cloneTemplate (Batch_Template__c newTemplate, Batch_Template_Field__c[] batchTemplateFields) {

        Boolean isSaved;
        templateRecord = newTemplate;
        templateFields = batchTemplateFields;

        Batch_Template__c templateToClone = new Batch_Template__c(Name = templateRecord.Name, Description__c = templateRecord.Description__c);

        // Insert template
        if (templateToClone != null) {

            try {
                insert templateToClone;
                isSaved = true;
                cloneTemplateFields(templateFields, templateToClone.Id);
            }
            catch (Exception ex) {
                isSaved = false;
            }
        }
        return isSaved;
    }

    public static Boolean editTemplate (Batch_Template__c newTemplate, Batch_Template_Field__c[] batchTemplateFields, Batch_Template_Field__c[] batchTemplateFieldsToDelete) {

        Boolean isSaved;
        templateRecord = newTemplate;
        templateFields = batchTemplateFields;
        templateFieldsToDelete = batchTemplateFieldsToDelete;

        // Update template
        if (templateRecord != null) {

            try {
                update templateRecord;
                saveTemplateFields(templateFields, templateRecord.Id);
                deleteTemplateFields(templateFieldsToDelete);
                isSaved = true;
            }
            catch (Exception ex) {
                isSaved = false;
            }
        }
        return isSaved;
    }

    private static void saveTemplateFields (Batch_Template_Field__c[] templateFields, Id templateId) {

        Batch_Template_Field__c[] templateFieldsToSave = new Batch_Template_Field__c[]{};

        for (Batch_Template_Field__c templateField : templateFields) {

            if (templateField.Batch_Template__c  == null) {

                templateField.Batch_Template__c = templateId;   
            }
            templateFieldsToSave.add(templateField);
        }

        if (!templateFieldsToSave.isEmpty()) {
            upsert templateFieldsToSave;
        }
    }

    private static void cloneTemplateFields (Batch_Template_Field__c[] templateFields, Id templateId) {

        Batch_Template_Field__c[] templateFieldsToSave = new Batch_Template_Field__c[]{};
        Batch_Template_Field__c templateToClone;

        for (Batch_Template_Field__c templateField : templateFields) {

            templateToClone =  new Batch_Template_Field__c(Batch_Template__c = templateId,
                                                            Name = templateField.Name,
                                                            Order__c = templateField.Order__c,
                                                            Read_Only__c = templateField.Read_Only__c,
                                                            Required__c = templateField.Required__c,
                                                            Sticky_Field__c = templateField.Sticky_Field__c,
                                                            Sticky_Field_Value__c = templateField.Sticky_Field_Value__c,
                                                            Sticky_Field_Visibility__c = templateField.Sticky_Field_Visibility__c);

            templateFieldsToSave.add(templateToClone);
        }

        if (!templateFieldsToSave.isEmpty()) {
            insert templateFieldsToSave;
        }
    }

    public static Boolean deleteTemplateFields (Batch_Template_Field__c[] templateFieldsToDelete) {

        Boolean result;

        if (!templateFieldsToDelete.isEmpty()) {

            try {
                delete templateFieldsToDelete;
                result = true;
            }
            catch (Exception ex) {
                result = false;
            }
        }

        return result;
    }

    public static Batch_Template_Field__c[] loadTemplateFields (Id templateId) {

        Batch_Template_Field__c[] templateFields = new Batch_Template_Field__c[]{};

        templateFields = [SELECT Id,
                                Name,
                                Order__c,
                                Read_Only__c,
                                Required__c,
                                Sticky_Field__c,
                                Sticky_Field_Value__c,
                                Sticky_Field_Visibility__c,
                                Batch_Template__c
                            FROM Batch_Template_Field__c
                            WHERE Batch_Template__c = :templateId
                            LIMIT 10000];

        if (templateFields.isEmpty()) {
            templateFields = null;
        }

        return templateFields;
    }

    //@AuraEnabled
    public static Batch_Template__c[] loadTemplates () {

        Batch_Template__c[] templates = new Batch_Template__c[]{};

        templates = [SELECT Id, Name, Description__c FROM Batch_Template__c];

        return templates;
    }
}