src/objects/Batch_Template_Field__c.object
<CustomObject>
    <fields>
        <fullName>Sticky_Field_Value__c</fullName>
        <description>This field stores the default value to be used if &quot;Sticky Field&quot; is true.</description>
        <inlineHelpText>This field stores the default value to be used if &quot;Sticky Field&quot; is true.</inlineHelpText>
        <label>Sticky Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sticky_Field_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked all Data Import records will have the specified field filled with the specified value, but it will not be shown in the grid. This is usefull in case that we have a constant value that we want to keep in the object but not show at the grid.</description>
        <inlineHelpText>If checked all Data Import records will have the specified field filled with the specified value, but it will not be shown in the grid. This is usefull in case that we have a constant value that we want to keep in the object but not show at the grid.</inlineHelpText>
        <label>Sticky Field Visibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sticky_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the field will be filled in with a default value.</description>
        <inlineHelpText>Indicates if the field will be filled in with a default value.</inlineHelpText>
        <label>Sticky Field</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Template Field</label>
    <nameField>
        <label>Batch Template Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Template Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DataImport__c.object
<CustomObject>
    <description>Custom object to hold denormalized data records that can be imported into the Nonprofit Success Pack.</description>
    <label>NPSP Data Import</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPSP Data Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BGE_DynamicalColumnWrapper.cls
public with sharing class BGE_DynamicalColumnWrapper {

	private static final Map<String, String> GRID_COLUMN_TYPES = new Map<String, String>
                                                                {  'STRING' => 'text',
																   'PICKLIST' => 'text',
                                                                   'DATE' => 'date',
                                                                   'DATETIME' => 'date',
                                                                   'ID' => 'text',
                                                                   'CURRENCY' => 'numeric',
                                                                   'BOOLEAN' => 'boolean',
                                                                   'NUMBER' => 'numeric',
                                                                   'DECIMAL' => 'numeric'
                                                                };

	public String apiName { get; set; }
	public String name { get; set; }
	public String type { get; set; }
	public String isDecimal { get; set; }
	public Boolean stickyField { get; set; }
	public String  stickyFieldValue { get; set; }
	public Boolean stickyFieldVisibility { get; set; }

	//Constructor
	public BGE_DynamicalColumnWrapper(Batch_Template_Field__c templateField) {

		Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
		Map <String, Schema.SObjectField> fieldMap = schemaMap.get('DataImport__c').getDescribe().fields.getMap();
		Schema.describefieldresult field = fieldMap.get(templateField.Name).getDescribe();

		apiName = templateField.Name;
		name = field.getLabel();
		isDecimal = 'false';
		type = String.valueOf(field.getType());

		stickyField = templateField.Sticky_Field__c;
		stickyFieldValue = templateField.Sticky_Field_Value__c;
		stickyFieldVisibility = templateField.Sticky_Field_Visibility__c;

		mapFieldTypes();

		system.debug('TEST ' + this);
	}

	private void mapFieldTypes() {

		if(type.equals('CURRENCY') || type.equals('DECIMAL')) {

			isDecimal = 'true';
		}

		if(GRID_COLUMN_TYPES.containsKey(type)) {

			type = GRID_COLUMN_TYPES.get(type);
		}
		else {
			type = 'text';
		}

	}
}