src/objects/Batch_Template__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Batch Template</label>
    <nameField>
        <label>BGE Batch Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DataImport__c.object
<CustomObject>
    <description>Custom object to hold denormalized data records that can be imported into the Nonprofit Success Pack.</description>
    <fields>
        <fullName>Account1ImportStatus__c</fullName>
        <label>Account1 Import Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account1Imported__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account1 Imported</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Data_Imports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account1_City__c</fullName>
        <inlineHelpText>Account1.BillingCity</inlineHelpText>
        <label>Account1 City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account1_Country__c</fullName>
        <inlineHelpText>Account1.BillingCountry</inlineHelpText>
        <label>Account1 Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account1_Name__c</fullName>
        <inlineHelpText>Account1.Name</inlineHelpText>
        <label>Account1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account1_Phone__c</fullName>
        <inlineHelpText>Account1.Phone</inlineHelpText>
        <label>Account1 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Account1_State_Province__c</fullName>
        <inlineHelpText>Account1.BillingState</inlineHelpText>
        <label>Account1 State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account1_Street__c</fullName>
        <inlineHelpText>Account1.BillingStreet</inlineHelpText>
        <label>Account1 Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Account1_Website__c</fullName>
        <inlineHelpText>Account1.Website</inlineHelpText>
        <label>Account1 Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Account1_Zip_Postal_Code__c</fullName>
        <inlineHelpText>Account1.BillingPostalCode</inlineHelpText>
        <label>Account1 Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account2ImportStatus__c</fullName>
        <label>Account2 Import Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account2Imported__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account2 Imported</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Data_Imports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account2_City__c</fullName>
        <inlineHelpText>Account2.BillingCity</inlineHelpText>
        <label>Account2 City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account2_Country__c</fullName>
        <inlineHelpText>Account2.BillingCountry</inlineHelpText>
        <label>Account2 Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account2_Name__c</fullName>
        <inlineHelpText>Account2.Name</inlineHelpText>
        <label>Account2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account2_Phone__c</fullName>
        <inlineHelpText>Account2.Phone</inlineHelpText>
        <label>Account2 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Account2_State_Province__c</fullName>
        <inlineHelpText>Account2.BillingState</inlineHelpText>
        <label>Account2 State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account2_Street__c</fullName>
        <inlineHelpText>Account2.BillingStreet</inlineHelpText>
        <label>Account2 Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Account2_Website__c</fullName>
        <inlineHelpText>Account2.Website</inlineHelpText>
        <label>Account2 Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Account2_Zip_Postal_Code__c</fullName>
        <inlineHelpText>Account2.BillingPostalCode</inlineHelpText>
        <label>Account2 Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApexJobId__c</fullName>
        <description>The ApexJobID of the Batch Job that processed the record.</description>
        <inlineHelpText>The ApexJobID of the Batch Job that processed the record.</inlineHelpText>
        <label>ApexJobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the batch object to be used by BGE.</description>
        <inlineHelpText>Lookup to the batch object to be used by BGE.</inlineHelpText>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>NPSP Data Imports</relationshipLabel>
        <relationshipName>NPSP_Data_Imports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Status__c</fullName>
        <label>Campaign Member Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact1ImportStatus__c</fullName>
        <label>Contact1 Import Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact1Imported__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact1 Imported</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Data_Imports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact1_Alternate_Email__c</fullName>
        <inlineHelpText>Contact1.npe01__AlternateEmail__c</inlineHelpText>
        <label>Contact1 Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact1_Birthdate__c</fullName>
        <inlineHelpText>Contact1.Birthdate</inlineHelpText>
        <label>Contact1 Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact1_Firstname__c</fullName>
        <inlineHelpText>Contact1.Firstname</inlineHelpText>
        <label>Contact1 First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact1_Home_Phone__c</fullName>
        <inlineHelpText>Contact1.HomePhone</inlineHelpText>
        <label>Contact1 Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact1_Lastname__c</fullName>
        <inlineHelpText>Contact1.Lastname</inlineHelpText>
        <label>Contact1 Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact1_Mobile_Phone__c</fullName>
        <inlineHelpText>Contact1.MobilePhone</inlineHelpText>
        <label>Contact1 Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact1_Other_Phone__c</fullName>
        <inlineHelpText>Contact1.OtherPhone</inlineHelpText>
        <label>Contact1 Other Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact1_Personal_Email__c</fullName>
        <inlineHelpText>Contact1.npe01__HomeEmail__c</inlineHelpText>
        <label>Contact1 Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact1_Preferred_Email__c</fullName>
        <inlineHelpText>Contact1.npe01__Preferred_Email__c</inlineHelpText>
        <label>Contact1 Preferred Email</label>
        <picklist>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact1_Preferred_Phone__c</fullName>
        <inlineHelpText>Contact1.npe01__PreferredPhone__c</inlineHelpText>
        <label>Contact1 Preferred Phone</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact1_Salutation__c</fullName>
        <inlineHelpText>Contact1.Salutation</inlineHelpText>
        <label>Contact1 Salutation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact1_Title__c</fullName>
        <inlineHelpText>Contact1.Title</inlineHelpText>
        <label>Contact1 Title</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact1_Work_Email__c</fullName>
        <inlineHelpText>Contact1.npe01__WorkEmail__c</inlineHelpText>
        <label>Contact1 Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact1_Work_Phone__c</fullName>
        <inlineHelpText>Contact1.npe01__WorkPhone__c</inlineHelpText>
        <label>Contact1 Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact2ImportStatus__c</fullName>
        <label>Contact2 Import Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact2Imported__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact2 Imported</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Data_Imports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact2_Alternate_Email__c</fullName>
        <inlineHelpText>Contact2.npe01__AlternateEmail__c</inlineHelpText>
        <label>Contact2 Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact2_Birthdate__c</fullName>
        <inlineHelpText>Contact2.Birthdate</inlineHelpText>
        <label>Contact2 Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact2_Firstname__c</fullName>
        <inlineHelpText>Contact2.Firstname</inlineHelpText>
        <label>Contact2 First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact2_Home_Phone__c</fullName>
        <inlineHelpText>Contact2.HomePhone</inlineHelpText>
        <label>Contact2 Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact2_Lastname__c</fullName>
        <inlineHelpText>Contact2.Lastname</inlineHelpText>
        <label>Contact2 Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact2_Mobile_Phone__c</fullName>
        <inlineHelpText>Contact2.MobilePhone</inlineHelpText>
        <label>Contact2 Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact2_Other_Phone__c</fullName>
        <inlineHelpText>Contact2.OtherPhone</inlineHelpText>
        <label>Contact2 Other Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact2_Personal_Email__c</fullName>
        <inlineHelpText>Contact2.npe01__HomeEmail__c</inlineHelpText>
        <label>Contact2 Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact2_Preferred_Email__c</fullName>
        <inlineHelpText>Contact2.npe01__Preferred_Email__c</inlineHelpText>
        <label>Contact2 Preferred Email</label>
        <picklist>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Donation_Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of importing the Data Import record.</description>
        <inlineHelpText>The status of importing the Data Import record.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Imported</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dry Run - Validated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dry Run - Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NPSP Data Import</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPSP Data Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DataImportBatch__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Approved&apos;</defaultValue>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NPSP Data Import Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPSP Data Import Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BGE_AuraController.cls
public with sharing class BGE_AuraController {
/*
	public static final String LIKE_OPERATOR = '%';

	@AuraEnabled
	public static Batch__c[] getActiveBatches(String stream) {
		return getBatchRecords(stream);
    }

	@AuraEnabled
	public static Batch__c[] getCompletedBatches(String stream) {
		return getBatchRecords(stream);
    }

	@AuraEnabled
	public static DataImport__c[] getDataImports(Id batchId) {
		return getDataImportRecords(batchId);
    }

	public static Batch__c[] getBatchRecords(String stream) {

		Batch__c[] result = new Batch__c[] {};

		if (!String.isEmpty(stream)) {

			stream = LIKE_OPERATOR + stream + LIKE_OPERATOR;

			result = [SELECT
						Id,
						Name,
						CreatedDate,
						LastModifiedDate,
						Description__c,
						Batch_Status__c
					FROM Batch__c
					WHERE Name
					LIKE :stream];
		}

		return result;
    }

	public static DataImport__c[] getDataImportRecords(Id batchId) {

		DataImport__c[] result = new DataImport__c[] {};

		result = [SELECT
					Account1_City__c,
					Account1_Country__c,
					Account1ImportStatus__c,
					Account1Imported__c,
					Account1_Name__c,
					Account1_Phone__c,
					Account1_State_Province__c,
					Account1_Street__c,
					Account1_Website__c,
					Account1_Zip_Postal_Code__c,
					Account2_City__c,
					Account2_Country__c,
					Account2ImportStatus__c,
					Account2Imported__c,
					Account2_Name__c,
					Account2_Phone__c,
					Account2_State_Province__c,
					Account2_Street__c,
					Account2_Website__c,
					Account2_Zip_Postal_Code__c,
					ApexJobId__c,
					Batch__c,
					Campaign_Member_Status__c,
					Donation_Campaign_Name__c,
					Contact1_Alternate_Email__c,
					Contact1_Birthdate__c,
					Contact1_Firstname__c,
					Contact1_Home_Phone__c,
					Contact1ImportStatus__c,
					Contact1Imported__c,
					Contact1_Lastname__c,
					Contact1_Mobile_Phone__c,
					Contact1_Other_Phone__c,
					Contact1_Personal_Email__c,
					Contact1_Preferred_Email__c,
					Contact1_Preferred_Phone__c,
					Contact1_Salutation__c,
					Contact1_Title__c,
					Contact1_Work_Email__c,
					Contact1_Work_Phone__c,
					Contact2_Alternate_Email__c,
					Contact2_Birthdate__c,
					Contact2_Firstname__c,
					Contact2_Home_Phone__c,
					Contact2ImportStatus__c,
					Contact2Imported__c,
					Contact2_Lastname__c,
					Contact2_Mobile_Phone__c,
					Contact2_Other_Phone__c,
					Contact2_Personal_Email__c,
					Contact2_Preferred_Email__c,
					Contact2_Preferred_Phone__c,
					Contact2_Salutation__c,
					Contact2_Title__c,
					Contact2_Work_Email__c,
					Contact2_Work_Phone__c,
					CreatedById,
					Name,
					Donation_Amount__c,
					Donation_Date__c,
					Donation_Description__c,
					Donation_Donor__c,
					DonationImportStatus__c,
					DonationImported__c,
					Donation_Member_Level__c,
					Donation_Membership_End_Date__c,
					Donation_Membership_Origin__c,
					Donation_Membership_Start_Date__c,
					Donation_Name__c,
					Donation_Possible_Matches__c,
					Donation_Record_Type_Name__c,
					Donation_Stage__c,
					Donation_Type__c,
					FailureInformation__c,
					HomeAddressImportStatus__c,
					HomeAddressImported__c,
					Home_City__c,
					Home_Country__c,
					Home_State_Province__c,
					Home_Street__c,
					Home_Zip_Postal_Code__c,
					HouseholdAccountImported__c,
					Household_Phone__c,
					ImportedDate__c,
					LastModifiedById,
					OwnerId,
					Payment_Check_Reference_Number__c,
					PaymentImportStatus__c,
					Payment_Method__c,
					PaymentImported__c,
					Status__c,
					Payment_Possible_Matches__c
				FROM DataImport__c
				WHERE Batch__c = :batchId];

		return result;
	}*/


	@AuraEnabled
    public static Id saveBatchTemplate (DataImportBatch__c batch, Id templateId) {

		Id result = BGE_TemplateController.saveBatch(batch,templateId);
		return result;
	}

	@AuraEnabled
    public static Id updateBatchTemplate (DataImportBatch__c batch, Id templateId) {

		Id result = BGE_TemplateController.updateBatch(batch,templateId);
		return result;
	}

	@AuraEnabled
    public static Boolean saveTemplate (Batch_Template__c newTemplate, Batch_Template_Field__c[] batchTemplateFields) {

		return BGE_TemplateController.saveTemplate (newTemplate, batchTemplateFields);
	}

	@AuraEnabled
    public static Boolean deleteTemplate (Id templateIdToDelete) {

		return BGE_TemplateController.deleteTemplate (templateIdToDelete);
	}

	@AuraEnabled
    public static Boolean cloneTemplate (Batch_Template__c newTemplate, Batch_Template_Field__c[] batchTemplateFields) {

		return BGE_TemplateController.cloneTemplate (newTemplate, batchTemplateFields);
	}

	@AuraEnabled
    public static Boolean editTemplate (Batch_Template__c newTemplate, Batch_Template_Field__c[] batchTemplateFields, Batch_Template_Field__c[] batchTemplateFieldsToDelete) {

		return BGE_TemplateController.editTemplate (newTemplate, batchTemplateFields, batchTemplateFieldsToDelete);
	}

	@AuraEnabled
    public static Batch_Template_Field__c[] loadTemplateFields (Id templateId) {

		return BGE_TemplateController.loadTemplateFields(templateId);
	}

	@AuraEnabled
    public static Batch_Template__c[] loadTemplates () {

		return BGE_TemplateController.loadTemplates();
	}

	@AuraEnabled
    public static void saveBatch (DataImportBatch__c newBatch) {

		BGE_BatchController.saveBatch(newBatch);
	}

	@AuraEnabled
    public static List<DataImportBatch__c> findByName(String searchKey) {

		return BGE_BatchController.findByName(searchKey);
	}


}